'use strict';
let adminTab='overview', adminReady=false;
function adminNode(tag,text,className) {const n=document.createElement(tag);if(text)n.textContent=text;if(className)n.className=className;return n;}
function setupAdmin() {
  if(adminReady)return;adminReady=true;
  const root=$('moderation');const nav=adminNode('nav',null,'admintabs');nav.setAttribute('aria-label','Administration tools');
  const panes=adminNode('div',null,'adminpanes');root.prepend(nav);root.append(panes);
  const items=[['overview','Overview',[]],['reviews','Mod reviews',[]],['members','Members',['memberlist']],['tickets','Support tickets',[]]];
  if(currentUser.role==='owner')items.push(['sections','Forum sections',['sectionmanager']],['invitations','Invitations',['ownercontrols']],['audit','Audit',['ownerlog']]);
  for(const [id,label,children]of items){const pane=adminNode('section');pane.id='admin-'+id;pane.hidden=id!==adminTab;panes.append(pane);for(const child of children)pane.append($(child));const b=button(label,()=>selectAdminTab(id));b.dataset.tab=id;nav.append(b);}
  $('admin-overview').append(adminNode('h3','Community overview'),adminNode('div',null,'adminmetrics'));$('admin-overview').lastChild.id='adminmetrics';
  $('admin-reviews').append(adminNode('h3','Pending mod reviews'),adminNode('p','Review the archive source before approving. Approval also publishes its imported dependencies. Owner imports publish automatically.'));
  const refresh=button('Refresh queue',loadModReviews);$('admin-reviews').append(refresh,adminNode('div',null,'admincards'));$('admin-reviews').lastChild.id='modreviewlist';
  const search=adminNode('input');search.id='adminmembersearch';search.placeholder='Search members…';search.setAttribute('aria-label','Search administrator member list');search.addEventListener('input',filterAdminMembers);$('admin-members').prepend(search);
  $('admin-tickets').append(adminNode('h3','Support tickets'),button('Refresh tickets',loadAdminTickets),adminNode('div',null,'ticketlayout'));const layout=$('admin-tickets').lastChild;
  const list=adminNode('div');list.id='adminticketlist';const detail=adminNode('div');detail.id='adminticketdetail';layout.append(list,detail);
  updateAdminTabs();
}
function updateAdminTabs(){document.querySelectorAll('.admintabs button').forEach(b=>{b.classList.toggle('active',b.dataset.tab===adminTab);b.setAttribute('aria-current',b.dataset.tab===adminTab?'page':'false');});}
async function selectAdminTab(id){adminTab=id;document.querySelectorAll('.adminpanes>section').forEach(p=>p.hidden=p.id!=='admin-'+id);updateAdminTabs();if(id==='tickets')await loadAdminTickets();if(id==='reviews')await loadModReviews();if(id==='overview')await loadAdminOverview();}
function filterAdminMembers(){const q=$('adminmembersearch').value.trim().toLowerCase();Array.from($('memberlist').children).forEach(n=>n.hidden=!n.dataset.search?.includes(q));}
async function loadAdminOverview(){const v=await(await api('admin/overview')).json();$('adminmetrics').replaceChildren(...['members','banned','unverified','mods','pending','topics','posts','sessions'].map(k=>{const c=adminNode('div',null,'metric');c.append(adminNode('strong',String(v[k])),adminNode('span',k==='pending'?'Awaiting review':k));return c;}));const p=adminNode('p',`Mod storage: ${(v.storage_bytes/1024**3).toFixed(2)} GiB · Server ${v.version}`);$('adminmetrics').append(p);}
async function loadModReviews(){const mods=await(await api('admin/mod-reviews')).json();$('modreviewlist').replaceChildren(...mods.map(m=>{const card=adminNode('article',null,'entry');card.append(adminNode('strong',m.name),adminNode('p',`${m.version} · ${m.author} · ${(m.size/1024**2).toFixed(1)} MiB · Game ${m.app_id||'Minecraft'}`));const tools=adminNode('div',null,'row');tools.append(button('Inspect source',()=>viewSource(m.id)),button('Approve with dependencies',async()=>{if(!confirm(`Publish ${m.name} and its imported dependencies?`))return;await json(`mods/${m.id}/approve`,{});await loadModReviews();await loadAdminOverview();message('Mod and its dependencies approved.');}),button('Reject / delete',async()=>{if(!confirm(`Permanently delete ${m.name}?`))return;await api(`mods/${m.id}`,{method:'DELETE'});await loadModReviews();await loadAdminOverview();}));card.append(tools);return card;}));if(!mods.length)$('modreviewlist').textContent='No mods awaiting review.';}
async function loadAdminTickets(){const rows=await(await api('admin/tickets')).json();$('adminticketlist').replaceChildren(...rows.map(t=>{const b=button(`${t.status.toUpperCase()} · ${t.subject} · ${t.category}`,()=>openAdminTicket(t.id));b.className='ticketlink';return b;}));if(!rows.length)$('adminticketlist').textContent='No support tickets yet.';}
async function openAdminTicket(id){const v=await(await api(`support/tickets/${id}`)).json();const detail=$('adminticketdetail');detail.replaceChildren(adminNode('h3',v.subject),adminNode('p',`${v.category} · ${v.status}`));for(const m of v.messages){const n=adminNode('article',null,'entry');n.append(adminNode('strong',m.staff?'Canna staff':'Ticket author'),adminNode('p',m.body,'postbody'),adminNode('small',activity(m.created)));detail.append(n);}const form=adminNode('form');const text=adminNode('textarea');text.rows=4;text.maxLength=10000;text.required=true;text.setAttribute('aria-label','Reply to ticket');const send=adminNode('button','Post staff reply');send.type='submit';form.append(text,send);form.hidden=v.status==='closed';form.addEventListener('submit',e=>{e.preventDefault();action(async()=>{send.disabled=true;try{await api(`support/tickets/${id}/reply`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body:text.value})});await openAdminTicket(id);}finally{send.disabled=false;}});});detail.append(form,button(v.status==='closed'?'Reopen ticket':'Close ticket',async()=>{if(!confirm(`${v.status==='closed'?'Reopen':'Close'} this ticket?`))return;await api(`admin/tickets/${id}/status`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:v.status==='closed'?'open':'closed'})});await openAdminTicket(id);await loadAdminTickets();}));if(currentUser.role==='owner' && v.status==='closed')detail.append(button('Delete closed ticket',async()=>{if(!confirm('Permanently delete this ticket and its replies?'))return;await api(`admin/tickets/${id}`,{method:'DELETE'});detail.replaceChildren();await loadAdminTickets();}));}
