'use strict';
let adminTab='overview', adminReady=false;
let invitationSettingsRevision=0;
function adminNode(tag,text,className) {const n=document.createElement(tag);if(text)n.textContent=text;if(className)n.className=className;return n;}
function setupAdmin() {
  if(adminReady)return;adminReady=true;
  const root=$('moderation');root.classList.add('adminworkspace');
  const heading=root.querySelector('h2');heading.textContent='Community control room';
  const header=adminNode('header',null,'adminhero');const intro=adminNode('div');intro.append(adminNode('p','CANNA / ADMINISTRATION','eyebrow'),heading,adminNode('p','Keep the community running. Review content, look after members and shape what happens next.'));
  const refresh=button('Refresh overview',loadAdminOverview);refresh.className='primary';header.append(intro,refresh);root.prepend(header);
  const summary=$('adminsummary');summary.className='adminsummary';header.after(summary);
  const nav=adminNode('nav',null,'admintabs');nav.setAttribute('aria-label','Administration tools');
  const sidebar=adminNode('aside',null,'adminsidebar');const search=adminNode('input');search.type='search';search.placeholder='Find a tool…';search.setAttribute('aria-label','Search administration tools');search.addEventListener('input',()=>{const q=search.value.toLowerCase();nav.querySelectorAll('button').forEach(b=>b.hidden=!b.textContent.toLowerCase().includes(q));});sidebar.append(search,nav);
  const panes=adminNode('div',null,'adminpanes');const adminLayout=adminNode('div',null,'adminlayout');adminLayout.append(sidebar,panes);root.append(adminLayout);
  const items=[['overview','Overview',[]],['reviews','Mod reviews',[]],['members','Members',['memberlist']],['tickets','Support tickets',[]],['community','Banner & chat',[]],['logs','Logs',['ownerlog']],['diagnostics','Rebound diagnostics',[]]];
  if(currentUser.role==='owner')items.push(['sections','Forum sections',['sectionmanager']],['invitations','Invitations',['ownercontrols']],['economy','Kash wallets',[]],['gambling','Gambling controls',[]]);
  const icons={overview:'◈',reviews:'✓',members:'♙',tickets:'✉',community:'◌',diagnostics:'◇',logs:'≡',sections:'▤',invitations:'+',economy:'K',gambling:'♠'};
  for(const [id,label,children]of items){const pane=adminNode('section');pane.id='admin-'+id;pane.hidden=id!==adminTab;panes.append(pane);for(const child of children)pane.append($(child));const b=button(label,()=>selectAdminTab(id));b.prepend(adminNode('span',icons[id],'adminnavicon'));b.dataset.tab=id;nav.append(b);}
  $('admin-overview').append(adminNode('h3','Community overview'),adminNode('div',null,'adminmetrics'));$('admin-overview').lastChild.id='adminmetrics';
  $('admin-reviews').append(adminNode('h3','Pending mod reviews'),adminNode('p','Inspect reconstructed source and resolve all findings before approval, including dependencies. Downloads wait for automatic analysis; findings require staff review.'));
  const queueRefresh=button('Refresh queue',loadModReviews);$('admin-reviews').append(queueRefresh,adminNode('div',null,'admincards'));$('admin-reviews').lastChild.id='modreviewlist';const queueStatus=adminNode('p');queueStatus.id='reviewqueuestatus';queueStatus.setAttribute('role','status');$('admin-reviews').insertBefore(queueStatus,$('modreviewlist'));
  const memberSearch=adminNode('input');memberSearch.id='adminmembersearch';memberSearch.placeholder='Search members…';memberSearch.setAttribute('aria-label','Search administrator member list');$('admin-members').prepend(adminNode('h3','Members & roles'),memberSearch);
  $('admin-tickets').append(adminNode('h3','Support tickets'),button('Refresh tickets',loadAdminTickets),adminNode('div',null,'ticketlayout'));const layout=$('admin-tickets').lastChild;
  const list=adminNode('div');list.id='adminticketlist';const detail=adminNode('div');detail.id='adminticketdetail';layout.append(list,detail);
  $('admin-logs').prepend(button('Refresh logs',loadAdminLogs));
  $('admin-diagnostics').append(adminNode('h3','Anonymous Rebound reports'),adminNode('p','Opt-in client reports, retained for seven days. Room tokens and actor numbers are anonymous; hashes are untrusted client claims. Reports do not change approvals or game settings.'),button('Refresh reports',loadReboundDiagnostics),adminNode('div',null,'admincards'));$('admin-diagnostics').lastChild.id='rebounddiagnosticlist';
  const logsearch=adminNode('input');logsearch.id='logsearch';logsearch.placeholder='Search actions, mods, reasons…';$('admin-logs').prepend(logsearch);
  if(currentUser.role==='owner'){$('admin-economy').append(adminNode('h3','Kash balances'),adminNode('p','Balance: a nonnegative whole number. Total earned: 0–1,000,000 (controls badge unlocks). Changes require a reason and are logged.'),button('Refresh balances',loadWallets),adminNode('div',null,'admincards'));$('admin-economy').lastChild.id='walletlist';}
  setupLoungeAdmin();
  if(currentUser.role==='owner'){setupInvitationHistory();setupInvitationSettings();if(typeof setupGamblingAdmin==='function')setupGamblingAdmin();}
  updateAdminTabs();
}
function updateAdminTabs(){document.querySelectorAll('.admintabs button').forEach(b=>{b.classList.toggle('active',b.dataset.tab===adminTab);b.setAttribute('aria-current',b.dataset.tab===adminTab?'page':'false');});}
async function selectAdminTab(id){adminTab=id;document.querySelectorAll('.adminpanes>section').forEach(p=>p.hidden=p.id!=='admin-'+id);updateAdminTabs();if(id==='invitations'){await loadInvitationHistory();await loadInvitationSettings();}if(id==='members')await loadAdminMembers();if(id==='sections')await loadSectionEditor();if(id==='logs')await loadAdminLogs();if(id==='diagnostics')await loadReboundDiagnostics();if(id==='economy')await loadWallets();if(id==='community')await loadLoungeAdmin();if(id==='tickets')await loadAdminTickets();if(id==='reviews')await loadModReviews();if(id==='overview')await loadAdminOverview();if(id==='gambling')await loadGamblingAdmin();}
function setupInvitationSettings(){
 const box=adminNode('section',null,'adminsettingcard');box.id='invitation-settings';box.append(adminNode('h3','Invitation & registration gates'),adminNode('p','Pause new invitation creation separately from account registration. Existing codes remain in history and resume working when registration reopens.'));
 const form=adminNode('form');for(const [id,title,detail]of [['admin-invites-paused','Pause new invitations','Members and the owner cannot generate new codes.'],['admin-registrations-paused','Pause new registrations','Existing accounts can still sign in; unused codes are preserved.']]){const row=adminNode('label',null,'adminswitch');const input=adminNode('input');input.type='checkbox';input.id=id;const label=adminNode('span');label.append(adminNode('strong',title),adminNode('small',detail));row.append(input,label);form.append(row);}
 const reason=adminNode('input');reason.id='admin-invitation-reason';reason.maxLength=500;reason.required=true;reason.minLength=5;reason.placeholder='Reason for this change (logged)';reason.setAttribute('aria-label','Reason for invitation policy change');const save=adminNode('button','Save invitation policy');save.type='submit';save.className='primary';const status=adminNode('p');status.id='admin-invitation-state';status.setAttribute('role','status');form.append(reason,save,status);
 form.addEventListener('submit',e=>{e.preventDefault();action(async()=>{save.disabled=true;try{await json('admin/invitation-settings',{invites_paused:$('admin-invites-paused').checked,registrations_paused:$('admin-registrations-paused').checked,reason:reason.value,revision:invitationSettingsRevision});await loadInvitationSettings();await refresh();message('Invitation policy saved.');}finally{save.disabled=false;}});});box.append(form);$('admin-invitations').prepend(box);
}
async function loadInvitationSettings(){const v=await(await api('admin/invitation-settings')).json();invitationSettingsRevision=v.revision;$('admin-invites-paused').checked=!!v.invites_paused;$('admin-registrations-paused').checked=!!v.registrations_paused;$('admin-invitation-reason').value=v.reason||'';$('admin-invitation-state').textContent=`New invitations ${v.invites_paused?'paused':'open'} · Registrations ${v.registrations_paused?'paused':'open'}`;}
function appendAdminMemberRoles(row,member){
 if(currentUser.role!=='owner')return;
 const label=adminNode('label',null,'adminswitch compact');const check=adminNode('input');check.type='checkbox';check.checked=(member.roles||[]).includes('beta');check.setAttribute('aria-label','Beta access for '+member.username);
 const text=adminNode('span');text.append(adminNode('strong','Beta access'),adminNode('small','Extra testing access; keeps the member’s existing role.'));label.append(check,text);row.append(label);
 check.addEventListener('change',()=>action(async()=>{const enabled=check.checked;check.disabled=true;try{await json('admin/users/'+member.id+'/roles',{roles:enabled?['beta']:[]});message(`${member.username}: Beta access ${enabled?'enabled':'removed'}.`);}catch(error){check.checked=!enabled;throw error;}finally{check.disabled=false;}}));
}
let inviteHistoryPage=1;
function setupInvitationHistory(){
 const controls=$('admin');controls.querySelector('h2').textContent='Generate invitations';
 const mode=adminNode('select');mode.id='invitemode';mode.setAttribute('aria-label','Generation mode');for(const [value,label]of [['wave','Invite wave (grouped codes)'],['codes','Individual invite codes']]){const option=adminNode('option',label);option.value=value;mode.append(option);}
 const label=adminNode('input');label.id='invitelabel';label.maxLength=80;label.placeholder='Label, e.g. Family October';label.setAttribute('aria-label','Invitation label');controls.prepend(mode,label);$('newwave').textContent='Generate invitations';
 const root=adminNode('section');root.append(adminNode('h2','Invitation history'),adminNode('p','New codes are saved here. Older hash-only invitations can be revoked, but their original codes cannot be recovered. Revoking an invite does not remove an account that already used it.'));
 const tools=adminNode('div',null,'row');const search=adminNode('input');search.id='invitehistorysearch';search.placeholder='Search issuer, recipient, code, wave or label…';search.setAttribute('aria-label','Search invitations');
 const sort=adminNode('select');sort.id='invitehistorysort';for(const [value,label]of [['newest','Newest first'],['oldest','Oldest first'],['user','By issuing user'],['most','Users with most invitations']]){const o=adminNode('option',label);o.value=value;sort.append(o);}
 const status=adminNode('select');status.id='invitehistorystatus';for(const value of ['','active','used','revoked','expired','closed']){const o=adminNode('option',value||'All statuses');o.value=value;status.append(o);}
 tools.append(search,sort,status,button('Search / refresh',()=>{inviteHistoryPage=1;return loadInvitationHistory();}));root.append(tools);for(const select of [sort,status])select.addEventListener('change',()=>action(async()=>{inviteHistoryPage=1;await loadInvitationHistory();}));search.addEventListener('keydown',e=>{if(e.key==='Enter')action(async()=>{inviteHistoryPage=1;await loadInvitationHistory();});});
 const list=adminNode('div');list.id='invitehistory';root.append(list);const pages=adminNode('div',null,'row');const previous=button('Previous',()=>{inviteHistoryPage--;return loadInvitationHistory();});previous.id='inviteprevious';const next=button('Next',()=>{inviteHistoryPage++;return loadInvitationHistory();});next.id='invitenext';const count=adminNode('span');count.id='invitehistorycount';pages.append(previous,count,next);root.append(pages);$('ownercontrols').append(root);
}
async function loadInvitationHistory(){
 if(currentUser.role!=='owner'||!$('invitehistory'))return;
 const q=new URLSearchParams({q:$('invitehistorysearch').value,sort:$('invitehistorysort').value,status:$('invitehistorystatus').value,page:inviteHistoryPage});const data=await(await api('invites?'+q)).json();
 $('invitehistory').replaceChildren(...data.items.map(i=>{
  const card=adminNode('article',null,'entry');const info=adminNode('div');info.append(adminNode('strong',`${i.issuer} · ${i.status}`),adminNode('p',`${i.label||'Unlabelled'} · ${i.wave?'Wave '+i.wave:'Individual code'} · Issuer total: ${i.issuer_count}`),adminNode('small',`${i.created?new Date(i.created*1000).toLocaleString():'Created before history'} · Expires ${new Date(i.expires*1000).toLocaleString()}${i.redeemed_by?' · Used by '+i.redeemed_by:''}`));
  if(i.code){const code=adminNode('input');code.readOnly=true;code.value=i.code;code.setAttribute('aria-label','Invitation code');const copyLink=button('Copy invite link',async()=>{await navigator.clipboard.writeText(invitationLink(i.code));message('Invitation link copied. It shares this code’s expiry and use limit.');});copyLink.disabled=i.status!=='active';info.append(code,copyLink,button('Copy code',async()=>{await navigator.clipboard.writeText(i.code);message('Code copied.');}));}else info.append(adminNode('p','Original code unavailable (legacy invitation)'));
  card.append(info);if(i.status==='active'){card.append(button('Revoke code',async()=>{if(!await cannaConfirm('Revoke this unused invitation?'))return;await api('invites/'+i.id,{method:'DELETE'});await loadInvitationHistory();}));if(i.wave)card.append(button('Revoke wave',async()=>{if(!await cannaConfirm('Revoke every unused invitation in this wave?'))return;await api('invite-waves/'+i.wave,{method:'DELETE'});await loadInvitationHistory();}));}return card;
 }));$('invitehistorycount').textContent=`Page ${data.page} · ${data.total} invitations`;$('inviteprevious').disabled=inviteHistoryPage<=1;$('invitenext').disabled=!data.has_more;
}
function filterAdminMembers(){const q=$('adminmembersearch').value.trim().toLowerCase();Array.from($('memberlist').children).forEach(n=>n.hidden=!n.dataset.search?.includes(q));}
async function loadAdminOverview(){const v=await(await api('admin/overview')).json();$('adminsummary').textContent=`${v.members} accounts · ${v.banned} banned · ${v.unverified} awaiting verification`;$('adminmetrics').replaceChildren(...['members','banned','unverified','mods','pending','topics','posts','sessions'].map(k=>{const c=adminNode('div',null,'metric');c.append(adminNode('strong',String(v[k])),adminNode('span',k==='pending'?'Awaiting review':k));return c;}));const p=adminNode('p',`Mod storage: ${(v.storage_bytes/1024**3).toFixed(2)} GiB · Server ${v.version}`);$('adminmetrics').append(p);}
async function loadModReviews(){const mods=await pagedList('admin/mod-reviews','modreviewlist',loadModReviews,null,data=>{if(data.queue)$('reviewqueuestatus').textContent=`${data.queue.scheduled} scheduled / processing · ${data.queue.waiting} waiting · ${data.queue.failed} failed. Shared dependencies first, then oldest imports.`;});$('modreviewlist').replaceChildren(...mods.map(m=>{const card=adminNode('article',null,'entry');card.append(adminNode('strong',m.name),adminNode('p',`${m.version} · ${m.author} · ${(m.size/1024**2).toFixed(1)} MiB · Game ${m.app_id||'Minecraft'}`));const state=m.analysis_status||'complete',unresolved=Number(m.unresolved_findings||0),blockers=m.dependency_blockers||[];const labels={pending:'Waiting for automatic analysis',queued:'Queued / processing',failed:'Analysis failed',complete:unresolved?`Needs review · ${unresolved} unresolved finding${unresolved===1?'':'s'}`:blockers.length?`Waiting for ${blockers.length} dependency review(s)`:'Analysis complete · staff approval required'};card.append(adminNode('p',labels[state]||state,'analysis-badge'));if(m.analysis_reason||m.review_reason)card.append(adminNode('small',m.analysis_reason||m.review_reason));for(const dep of blockers.slice(0,3)){const link=adminNode('a',`${dep.name}: ${dep.status==='complete'?dep.unresolved+' finding(s) need review':dep.status}`);link.href='/review/mods/'+encodeURIComponent(dep.id);link.className='helpbutton';card.append(link);}const status=adminNode('p');status.setAttribute('role','status');const tools=adminNode('div',null,'row');const approve=button('Approve with dependencies',async()=>{if(!await cannaConfirm(`Publish ${m.name} and its imported dependencies?`))return;approve.disabled=true;status.textContent='Approving mod and dependencies…';try{await json(`mods/${m.id}/approve`,{});await loadModReviews();await loadAdminOverview();message('Mod and its dependencies approved.');}catch(error){status.textContent=error.message||'Approval failed. Inspect source to review analysis and findings.';}finally{approve.disabled=false;}});approve.disabled=state!=='complete'||unresolved>0||blockers.length>0;if(state==='failed')tools.append(button('Retry analysis',async()=>{await json(`mods/${m.id}/analysis`,{force:true});await loadModReviews();}));tools.append(button('Inspect source',()=>viewSource(m.id)),approve,button('Deny with reason',()=>denyMod(m.id))); card.append(tools,status);return card;}));if(!mods.length)$('modreviewlist').textContent='No mods awaiting review.';}
async function loadAdminTickets(){const rows=await pagedList('admin/tickets','adminticketlist',loadAdminTickets);$('adminticketlist').replaceChildren(...rows.map(t=>{const b=button(`${t.status.toUpperCase()} · ${t.subject} · ${t.category}`,()=>openAdminTicket(t.id));b.className='ticketlink';return b;}));if(!rows.length)$('adminticketlist').textContent='No support tickets yet.';}
async function openAdminTicket(id){const v=await(await api(`support/tickets/${id}`)).json();const detail=$('adminticketdetail');detail.replaceChildren(adminNode('h3',v.subject),adminNode('p',`${v.category} · ${v.status}`));for(const m of v.messages){const n=adminNode('article',null,'entry');n.append(adminNode('strong',m.staff?'Canna staff':'Ticket author'),adminNode('p',m.body,'postbody'),adminNode('small',activity(m.created)));detail.append(n);}const form=adminNode('form');const text=adminNode('textarea');text.rows=4;text.maxLength=10000;text.required=true;text.setAttribute('aria-label','Reply to ticket');const send=adminNode('button','Post staff reply');send.type='submit';form.append(text,send);form.hidden=v.status==='closed';form.addEventListener('submit',e=>{e.preventDefault();action(async()=>{send.disabled=true;try{await api(`support/tickets/${id}/reply`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body:text.value})});await openAdminTicket(id);}finally{send.disabled=false;}});});detail.append(form,button(v.status==='closed'?'Reopen ticket':'Close ticket',async()=>{if(!await cannaConfirm(`${v.status==='closed'?'Reopen':'Close'} this ticket?`))return;await api(`admin/tickets/${id}/status`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:v.status==='closed'?'open':'closed'})});await openAdminTicket(id);await loadAdminTickets();}));if(currentUser.role==='owner' && v.status==='closed')detail.append(button('Delete closed ticket',async()=>{if(!await cannaConfirm('Permanently delete this ticket and its replies?'))return;await api(`admin/tickets/${id}`,{method:'DELETE'});detail.replaceChildren();await loadAdminTickets();}));}

async function loadAdminLogs(){const rows=await pagedList('admin/audit','auditlog',loadAdminLogs,'logsearch');$('ownerlog').hidden=false;$('auditlog').replaceChildren(...rows.map(e=>{const card=adminNode('article',null,'entry');let detail=e.target,target;try{target=JSON.parse(e.target);detail=JSON.stringify(target,null,2);}catch{}card.append(adminNode('strong',e.action),adminNode('small',new Date(e.created*1000).toLocaleString()+' · '+e.actor),adminNode('pre',detail,'postbody'));if(target?.mod){const link=adminNode('a','Open mod review');link.href='/review/mods/'+encodeURIComponent(target.mod);card.append(link);}return card;}));if(!rows.length)$('auditlog').textContent='No logged events yet.';}
async function loadWallets(){const rows=await pagedList('admin/wallets','walletlist',loadWallets);$('walletlist').replaceChildren(...rows.map(w=>{const card=adminNode('form',null,'entry');card.append(adminNode('strong',w.username));const balance=adminNode('input'),earned=adminNode('input'),reason=adminNode('input');for(const [input,label,value,max]of [[balance,'Kash balance',w.balance,Number.MAX_SAFE_INTEGER],[earned,'Total Kash earned',w.earned,1000000]]){input.type='number';input.min=0;input.max=max;input.required=true;input.value=value;input.setAttribute('aria-label',label);card.append(adminNode('label',label),input);}reason.placeholder='Reason for adjustment';reason.minLength=5;reason.maxLength=500;reason.required=true;card.append(reason);const save=adminNode('button','Save Kash');save.type='submit';card.append(save);card.addEventListener('submit',e=>{e.preventDefault();action(async()=>{if(!await cannaConfirm('Set '+w.username+' to '+balance.value+' Kash and '+earned.value+' total earned? This will be logged.'))return;save.disabled=true;try{await json('admin/wallets/'+w.id,{balance:Number(balance.value),earned:Number(earned.value),reason:reason.value});await loadWallets();message('Kash updated.');}finally{save.disabled=false;}});});return card;}));}

async function loadReboundDiagnostics(){
 const data=await api('admin/rebound-diagnostics');const root=$('rebounddiagnosticlist');root.replaceChildren();
 const sessions=new Map();for(const row of data.reports||[]){const r=row.report;if(!r||!r.session)continue;if(!sessions.has(r.session))sessions.set(r.session,new Map());const actors=sessions.get(r.session);if(!actors.has(r.actor))actors.set(r.actor,row);}
 for(const [session,actors]of sessions){const card=adminNode('article',null,'entry');card.append(adminNode('strong','Room token '+session),adminNode('small',actors.size+' reporting actor(s) · latest snapshot per actor'));const reports=[...actors.values()];
  for(const row of reports){const r=row.report;card.append(adminNode('p','Actor '+r.actor+' · guard '+r.guard_version+' · '+r.category+' · '+new Date(row.created*1000).toLocaleString()));const peers=[...actors.values()].filter(v=>v.report.actor!==r.actor).map(v=>v.report.local);for(const peer of r.peers||[])if(!peers.some(v=>v.actor===peer.actor))peers.push(peer);
   for(const peer of peers){const changed=['game','mods','assets','config','content'].filter(key=>r.local[key]!==peer[key]);card.append(adminNode('p','Compared with actor '+peer.actor+': '+(changed.length?'different '+changed.join(', '):'all reported hashes match')));const left=new Map((r.local.files||[]).map(f=>[f.key,f.sha256]));const right=new Map((peer.files||[]).map(f=>[f.key,f.sha256]));const files=[...new Set([...left.keys(),...right.keys()])].filter(key=>left.get(key)!==right.get(key));if(files.length)card.append(adminNode('small','Differing config groups: '+files.map(key=>key.startsWith('other:')?'other config '+key.slice(6,18):key).join(', ')));}
   const details=adminNode('details');details.append(adminNode('summary','Inspect anonymous hashes'),adminNode('pre',JSON.stringify(r,null,2),'postbody'));card.append(details);
  }root.append(card);
 }if(!sessions.size)root.textContent='No anonymous reports yet. Each player can opt in from the Rebound warning in ROUNDS.';
}
