 'use strict';
let loungeReady=false,announcementRevision=0,chatHistory=[],chatHistoryIndex=-1,chatDraft='';
let chatPendingTip=null,tipSuggestions=[],tipSuggestionIndex=-1,tipSearchGeneration=0,tipSearchTimer;
function loungeNode(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
function setupLounge(){
 if(loungeReady)return;loungeReady=true;
 const banner=loungeNode('aside',undefined,'announcementbanner');banner.id='announcementbanner';banner.hidden=true;banner.setAttribute('aria-label','Community announcement');
 const box=loungeNode('details',undefined,'globalchat');box.id='globalchat';box.open=!(window.matchMedia?.('(max-width:760px)')?.matches);
 const summary=loungeNode('summary','Community live chat');summary.append(loungeNode('small','Messages expire after 24 hours'));
 const list=loungeNode('div',undefined,'chatmessages');list.id='chatmessages';list.setAttribute('aria-label','Recent chat messages');
 const form=loungeNode('form');form.id='chatform';const input=loungeNode('input');input.id='chatbody';input.maxLength=1000;input.required=true;input.placeholder='Say something to the community…';input.setAttribute('aria-label','Chat message');
 input.addEventListener('keydown',event=>{if(handleTipKeys(event,input)||event.isComposing||event.altKey||event.ctrlKey||event.metaKey||event.shiftKey||!['ArrowUp','ArrowDown'].includes(event.key)||!chatHistory.length)return;if(event.key==='ArrowUp'){if(chatHistoryIndex<0){chatDraft=input.value;chatHistoryIndex=chatHistory.length-1;}else chatHistoryIndex=Math.max(0,chatHistoryIndex-1);}else{if(chatHistoryIndex<0)return;chatHistoryIndex++;if(chatHistoryIndex>=chatHistory.length)chatHistoryIndex=-1;}event.preventDefault();input.value=chatHistoryIndex<0?chatDraft:chatHistory[chatHistoryIndex];refreshTipSuggestions(input);});
 input.addEventListener('input',()=>{if(chatHistoryIndex>=0){chatHistoryIndex=-1;chatDraft=input.value;}});
 const send=loungeNode('button','Send');send.className='primary';send.type='submit';const status=loungeNode('p','');status.id='chatstatus';status.setAttribute('role','status');
 form.append(input,send);setupTipAutocomplete(input,form);form.addEventListener('submit',e=>{e.preventDefault();action(async()=>{send.disabled=true;let submitted=false,recorded=false;const body=input.value.trim(),isTip=/^\/tip(?:\s|$)/.test(body),member=currentUser?.id;try{if(chatPendingTip&&(chatPendingTip.body!==body||chatPendingTip.member!==member))throw new Error('Retry your pending tip with its original message and account first.');const pending=chatPendingTip||(isTip?{body,member,request_id:crypto.randomUUID()}:null);if(!Number.isSafeInteger(member))throw new Error('Sign in again before sending.');if(isTip)chatPendingTip=pending;submitted=true;await json('chat',{body,...(pending?{request_id:pending.request_id}:{})},{headers:{'X-Canna-Member':String(member)}});recorded=true;chatPendingTip=null;input.value='';chatHistoryIndex=-1;chatDraft='';hideTipSuggestions();status.textContent='';await loadChat(true);}catch(error){if(isTip&&submitted&&!recorded&&(!Number.isInteger(error.status)||error.status>=500))status.textContent='Tip result was not confirmed. Send the same message again to retry without a second charge.';else{if(submitted)chatPendingTip=null;status.textContent=recorded?'Message recorded. Refresh to load the latest chat.':error.message;}}finally{send.disabled=false;}});});
 const commands=loungeNode('div',undefined,'chatcommands');commands.append(loungeNode('small','CannaBot'));for(const command of ['/help','/fish','/daily','/balance','/collection','/coinflip','/tip','/badges']){const b=loungeNode('button',command);b.type='button';b.addEventListener('click',()=>{input.value=command==='/tip'?'/tip ':command;chatHistoryIndex=-1;chatDraft=input.value;input.focus();refreshTipSuggestions(input);});commands.append(b);}box.append(summary,list,commands,form,status);$('space').insertBefore(banner,$('space').children[1]);banner.after(box);
}
function hideTipSuggestions(){tipSearchGeneration++;clearTimeout(tipSearchTimer);tipSuggestions=[];tipSuggestionIndex=-1;const list=$('tip-suggestions');if(list){list.hidden=true;list.replaceChildren();}$('chatbody')?.setAttribute('aria-expanded','false');$('chatbody')?.removeAttribute('aria-activedescendant');}
function setupTipAutocomplete(input,form){const list=loungeNode('div',undefined,'tipsuggestions');list.id='tip-suggestions';list.hidden=true;list.setAttribute('role','listbox');list.setAttribute('aria-label','Choose a member to tip');input.setAttribute('aria-autocomplete','list');input.setAttribute('aria-controls',list.id);input.setAttribute('aria-expanded','false');form.append(list);input.addEventListener('input',()=>refreshTipSuggestions(input));}
function chooseTipSuggestion(index,input){const member=tipSuggestions[index];if(!member)return;input.value=`/tip @${member.username} `;chatHistoryIndex=-1;chatDraft=input.value;hideTipSuggestions();input.focus();}
function handleTipKeys(event,input){if($('tip-suggestions')?.hidden!==false||!tipSuggestions.length||event.isComposing)return false;if(event.key==='Escape'){hideTipSuggestions();event.preventDefault();return true;}if(['ArrowDown','ArrowUp'].includes(event.key)){event.preventDefault();tipSuggestionIndex=tipSuggestionIndex<0?(event.key==='ArrowDown'?0:tipSuggestions.length-1):(tipSuggestionIndex+(event.key==='ArrowDown'?1:-1)+tipSuggestions.length)%tipSuggestions.length;for(const [i,node]of [...$('tip-suggestions').children].entries())node.setAttribute('aria-selected',String(i===tipSuggestionIndex));input.setAttribute('aria-activedescendant','tip-option-'+tipSuggestionIndex);return true;}if(['Enter','Tab'].includes(event.key)&&tipSuggestionIndex>=0){event.preventDefault();chooseTipSuggestion(tipSuggestionIndex,input);return true;}return false;}
function refreshTipSuggestions(input){
 const match=/^\/tip\s+@?([^\s]*)$/.exec(input.value);hideTipSuggestions();if(!match)return;const term=match[1],generation=tipSearchGeneration,member=currentUser?.id;
 tipSearchTimer=setTimeout(async()=>{try{const data=await(await api('chat/tip-recipients?search='+encodeURIComponent(term))).json();if(generation!==tipSearchGeneration||input.value!==match[0]||currentUser?.id!==member)return;tipSuggestions=(Array.isArray(data)?data:data.items||[]).filter(m=>m.id!==member&&m.username.toLowerCase().startsWith(term.toLowerCase())).slice(0,8);const list=$('tip-suggestions');list.replaceChildren(...tipSuggestions.map((m,i)=>{const b=loungeNode('button','@'+m.username);b.type='button';b.id='tip-option-'+i;b.setAttribute('role','option');b.setAttribute('aria-selected','false');b.addEventListener('click',()=>chooseTipSuggestion(i,input));return b;}));list.hidden=!tipSuggestions.length;input.setAttribute('aria-expanded',String(!list.hidden));}catch{if(generation===tipSearchGeneration)hideTipSuggestions();}},180);
}
async function loadChat(forceBottom=false){
 setupLounge();const me=await(await api('me')).json();$('kashbalance').textContent=(me.kash||0).toLocaleString()+' Kash';const rows=await(await api('chat')).json(),list=$('chatmessages');if(chatHistoryIndex<0)chatHistory=await(await api('chat/history')).json();const bottom=forceBottom||list.scrollTop+list.clientHeight>=list.scrollHeight-32;
 list.replaceChildren(...rows.filter(m=>m.created*1000>Date.now()-86400000).map(m=>{
   const row=loungeNode('div',undefined,'chatline');row.dataset.created=m.created;
   const who=loungeNode('button',m.bot?'CannaBot':m.username,'chatwho');who.type='button';if(!m.bot)who.addEventListener('click',()=>action(()=>openProfile(m.user_id)));else who.disabled=true;
   const time=loungeNode('time',new Date(m.created*1000).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}));time.dateTime=new Date(m.created*1000).toISOString();
   row.append(time,who);if(!m.bot && ['angler','emerald','legend'].includes(m.badge)){const badge=loungeNode('small',undefined,'chatbadge');const label=({angler:'Mint Stripes',emerald:'Emerald Veins',legend:'Amethyst Spots'})[m.badge];badge.title=label;badge.setAttribute('aria-label',label+' leaf skin');badge.append(loungeNode('span',undefined,'cannaleaf leaf-'+m.badge));row.append(badge);}row.append(loungeNode('span',m.body,'chattext'));
   if(currentUser?.admin || m.user_id===currentUser?.id){const remove=loungeNode('button','×','chatdelete');remove.type='button';remove.setAttribute('aria-label',`Delete ${m.username}'s message`);remove.addEventListener('click',()=>action(async()=>{if(!await cannaConfirm('Delete this chat message?'))return;await api(`chat/${m.id}`,{method:'DELETE'});await loadChat();}));row.append(remove);}return row;
 }));if(!list.children.length)list.append(loungeNode('p','No messages yet. Start a conversation.','sidehint'));if(bottom)list.scrollTop=list.scrollHeight;
}
async function loadAnnouncement(){setupLounge();const v=await(await api('announcement')).json();const banner=$('announcementbanner');banner.textContent=v.body;banner.hidden=!v.active;return v;}
async function loadLoungeAdmin(){const v=await(await api('announcement')).json();announcementRevision=v.revision;$('announcementbody').value=v.body;$('announcementactive').checked=v.active;}
function setupLoungeAdmin(){
 const pane=$('admin-community');pane.append(loungeNode('h3','Announcement banner'));const form=loungeNode('form');
 const label=loungeNode('label','Announcement text');label.htmlFor='announcementbody';const text=loungeNode('textarea');text.id='announcementbody';text.maxLength=2000;text.rows=4;
 const active=loungeNode('label');active.className='check';const toggle=loungeNode('input');toggle.type='checkbox';toggle.id='announcementactive';active.append(toggle,document.createTextNode('Show banner to signed-in members'));
 const send=loungeNode('button','Review & apply banner');send.className='primary';send.type='submit';form.append(label,text,active,send);
 form.addEventListener('submit',e=>{e.preventDefault();action(async()=>{const draft={body:text.value,active:toggle.checked,revision:announcementRevision};if(!await cannaConfirm(draft.active?`Publish this announcement?\n\n${draft.body}`:'Hide the announcement banner?',{title:'Review announcement',label:'Apply announcement'}))return;send.disabled=true;try{await json('admin/announcement',draft);await loadLoungeAdmin();await loadAnnouncement();message('Announcement updated.');}finally{send.disabled=false;}});});
 pane.append(form,loungeNode('h3','Live chat moderation'),loungeNode('p','Delete individual messages in the chat, or clear the current chat history. Daily anti-spam allowances remain in place.'),button('Clear global chat',async()=>{if(!await cannaConfirm('Delete all current global chat messages?',{title:'Clear community chat',label:'Clear chat'}))return;await json('admin/chat/clear',{});await loadChat();}));
}
setInterval(()=>{const list=$('chatmessages');if(list)for(const row of Array.from(list.children))if(row.dataset.created && Number(row.dataset.created)*1000<=Date.now()-86400000)row.remove();},30000);
