 'use strict';
let denialMod;
async function loadNotifications(){const rows=await(await api('notifications')).json();$('notificationsnav').textContent=`Notifications${rows.some(n=>!n.read)?` (${rows.filter(n=>!n.read).length})`:''}`;$('clearnotifications').disabled=!rows.length;$('notificationlist').replaceChildren(...rows.map(n=>{const card=adminNodeSafe('article',undefined,'entry');const b=button(n.body,async()=>{await json('notifications/read',{id:n.id});await loadNotifications();if(n.link==='#submissions')await showView('submissionsview');else if(n.link==='#chat'){$('globalchat').open=true;$('chatbody').value='/daily';$('chatbody').focus();}else if(n.kind==='beta-invite'&&/^#invite-share\/[A-Za-z0-9_-]{1,64}$/.test(n.link)){await navigator.clipboard.writeText(invitationLink(n.link.slice(14)));message('Beta invitation link copied. Share it with one friend.');}else if(n.link==='#profile')await openProfile(currentUser.id);else if(n.link.startsWith('#thread/')){await loadThread(n.link.slice(8));}});if(!n.read)b.className='primary';card.append(b,adminNodeSafe('small',activity(n.created)));return card;}));if(!rows.length)$('notificationlist').textContent='No notifications yet.';}
function adminNodeSafe(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
async function loadSubmissions(){const rows=await(await api('submissions')).json();$('submissionlist').replaceChildren(...rows.map(m=>{const card=adminNodeSafe('article',undefined,'entry');const info=adminNodeSafe('div');info.append(adminNodeSafe('strong',`${m.name} · ${m.version}`),adminNodeSafe('p',`${m.status.toUpperCase()}${m.analysis?' · analysis '+m.analysis:''}`));if(m.reason)info.append(adminNodeSafe('p',m.reason,'postbody'));if(m.resolved)info.append(adminNodeSafe('small',`Clears ${new Date((m.resolved+604800)*1000).toLocaleString()}`));card.append(info);return card;}));if(!rows.length)$('submissionlist').textContent='No current submissions. Upload a mod or import an external project from Mods & modpacks.';}
$('submissionsnav').addEventListener('click',()=>action(()=>showView('submissionsview')));$('notificationsnav').addEventListener('click',()=>action(()=>showView('notificationsview')));$('readnotifications').addEventListener('click',()=>action(async()=>{await json('notifications/read',{});await loadNotifications();}));
function denyMod(id){denialMod=id;$('denyreason').value='';$('denymod').showModal();$('denyreason').focus();}
$('canceldeny').addEventListener('click',()=>$('denymod').close());$('denyform').addEventListener('submit',event=>{event.preventDefault();action(async()=>{const reason=$('denyreason').value;const id=denialMod;if(!await cannaConfirm(`Deny this mod and remove its file?\n\nReason: ${reason}`,{title:'Confirm mod denial',label:'Deny submission'}))return;await json(`mods/${id}/deny`,{reason});$('denymod').close();await loadModReviews();await loadAdminOverview();message('Submission denied; its author has been notified.');});});

$('clearnotifications').addEventListener('click',()=>action(async()=>{if(!await cannaConfirm('Delete all your notifications, including read notifications?',{title:'Clear notifications',label:'Clear all'}))return;const button=$('clearnotifications');button.disabled=true;try{await json('notifications/clear',{});await loadNotifications();message('Notifications cleared.');}finally{button.disabled=!$('notificationlist').children.length;}}));
