 'use strict';
const $=id=>document.getElementById(id),modId=location.pathname.split('/').at(-1);
let report={files:[],findings:[],observations:[]},selectedFile='',poll,decisionTarget;
function node(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
async function api(path,body){const response=await fetch('/api/v1/'+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});if(!response.ok){let error;try{error=await response.json();}catch{}throw Error(error?.error||`Request failed (${response.status})`);}return response.json();}
function highlight(text){
 const fragment=document.createDocumentFragment(),pattern=/(\/\/.*$|#[^\n]*$|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|\b(?:public|private|protected|static|class|interface|namespace|using|return|if|else|for|foreach|while|new|try|catch|throw|async|await|void|int|string|bool|true|false|null|import|package|def|fn|let|const|function|var|extends|implements)\b|\b\d+(?:\.\d+)?\b)/g;
 let last=0;for(const match of text.matchAll(pattern)){fragment.append(document.createTextNode(text.slice(last,match.index)));const t=match[0],kind=t.startsWith('//')||t.startsWith('#')?'comment':t.startsWith('"')||t.startsWith("'")?'string':/^\d/.test(t)?'number':'keyword';fragment.append(node('span',t,'syntax-'+kind));last=match.index+t.length;}fragment.append(document.createTextNode(text.slice(last)));return fragment;
}
function codeFile(name,line){selectedFile=name;const file=report.files.find(f=>f.name===name);if(!file)return;$('filename').textContent=file.name;$('filekind').textContent=file.kind==='decompiled'?'Reconstructed source':'Uploaded source';
 const lines=file.text.split('\n');let start=0,end=Math.min(lines.length,10000);if(line>10000){start=Math.max(0,line-200);end=Math.min(lines.length,line+200);}
 const nodes=[];if(start||end<lines.length)nodes.push(node('p',`Showing lines ${start+1}–${end} of ${lines.length}.`,'sidehint'));
 for(let i=start;i<end;i++){const row=node('div',undefined,'codeline');row.id='line-'+(i+1);row.append(node('span',String(i+1),'linenumber'));const code=node('code');code.append(highlight(lines[i]));row.append(code);if(i+1===line)row.classList.add('flaggedline');nodes.push(row);}$('code').replaceChildren(...nodes);if(line)$('line-'+line)?.scrollIntoView({block:'center'});
}
function renderFiles(){const query=$('filesearch').value.trim().toLowerCase();const files=report.files.filter(f=>f.name.toLowerCase().includes(query)||(query&&f.text.toLowerCase().includes(query)));$('filecount').textContent=`${files.length} source files`;
 const root=node('div');const groups=new Map();for(const file of files){const parts=file.name.split('/');let parent=root,path='';for(const part of parts.slice(0,-1)){path+='/'+part;if(!groups.has(path)){const detail=node('details');detail.open=parts.length<4||!!query;detail.append(node('summary',part));parent.append(detail);groups.set(path,detail);}parent=groups.get(path);}const b=node('button',parts.at(-1),'filelink');b.title=file.name;b.addEventListener('click',()=>codeFile(file.name));parent.append(b);}$('filetree').replaceChildren(root);$('inventory').replaceChildren(...(report.inventory||[]).map(f=>node('p',`${f.name} · ${(f.size/1024).toFixed(1)} KiB`)));}
function sourceLink(location){const link=node('button',location.file?`${location.file}${location.line?`:${location.line}`:''}`:'Archive / binary evidence');link.disabled=!location.file||!report.files.some(file=>file.name===location.file);link.addEventListener('click',()=>codeFile(location.file,location.line));return link;}
function appendEvidence(card,item){
 card.append(sourceLink(item),node('pre',item.evidence||'Review the analysis coverage and archive.'));
 if(item.context)card.append(node('p',`Context: ${item.context}`));
 const locations=(item.locations||[]).filter(location=>location.file!==item.file||location.line!==item.line||location.evidence!==item.evidence);
 if(locations.length){const detail=node('details');detail.append(node('summary',`${locations.length} related evidence ${locations.length===1?'location':'locations'}`));for(const location of locations){const row=node('div');row.append(sourceLink(location));if(location.evidence)row.append(node('pre',location.evidence));detail.append(row);}card.append(detail);}
}
function renderObservations(){const rows=report.observations||[];$('observations').replaceChildren(...rows.map(observation=>{const card=node('article',undefined,'finding');card.append(node('strong',`Informational · ${observation.title}`));appendEvidence(card,observation);return card;}));if(!rows.length)$('observations').textContent='No informational observations in this report.';}
function renderFindings(){const filter=$('findingfilter').value,rows=report.findings.filter(f=>filter==='all'||(filter==='accepted'?f.accepted:!f.accepted));$('findings').replaceChildren(...rows.map(f=>{const card=node('article',undefined,'finding');card.append(node('strong',`${f.accepted?'Accepted review decision':'Review required'} · ${f.severity} · ${f.title}`));appendEvidence(card,f);if(f.reason)card.append(node('p',`Review reason: ${f.reason}`));if(report.status==='rejected')return card;const b=node('button',f.accepted?'Reopen finding':'Accept finding with reason');b.addEventListener('click',()=>{decisionTarget=f;$('decisiontitle').textContent=f.accepted?'Reopen finding':'Accept finding';$('decisionevidence').textContent=f.title+' · '+(f.file||'archive');$('decisionreason').value='';$('findingdecision').showModal();$('decisionreason').focus();});card.append(b);return card;}));if(!rows.length)$('findings').textContent=filter==='open'?'No unresolved findings in this report. Review the source and coverage before approving.':'No findings in this view.';
 $('approve').disabled=report.status!=='complete'||report.findings.some(f=>!f.accepted);
}
async function load(){clearTimeout(poll);try{report=await api(`mods/${modId}/analysis`);report.files||=[];report.findings||=[];report.observations||=[];$('modname').textContent=report.mod_name;if(report.status==='rejected')report.error='Denied by policy: packing, obfuscation or malware signature detected. See findings and Admin panel Logs.';$('reviewstatus').textContent=`Analysis: ${report.status}${report.error?' · '+report.error:''} · ${report.findings.length} findings · ${report.observations.length} informational observations`;$('engines').textContent=report.engines?Object.entries(report.engines).map(([k,v])=>`${k}: ${v.status} ${v.version||''}`).join(' · '):'';renderFiles();renderFindings();renderObservations();if(selectedFile&&report.files.some(f=>f.name===selectedFile))codeFile(selectedFile);else if(report.files.length)codeFile(report.files[0].name);
 if(report.status==='pending'){try{await api(`mods/${modId}/analysis`,{});}catch(error){$('reviewstatus').textContent=error.message;}poll=setTimeout(load,4000);}else if(report.status==='queued')poll=setTimeout(load,2500);
 }catch(error){$('reviewstatus').textContent=error.message;}}
$('rescan').addEventListener('click',async()=>{if(!await cannaConfirm('Run analysis again? Previous finding decisions will be replaced, and downloads stay blocked until the new report is reviewed.'))return;try{await api(`mods/${modId}/analysis`,{force:true});await load();}catch(error){$('reviewstatus').textContent=error.message;}});
$('approve').addEventListener('click',async()=>{if(!await cannaConfirm('Publish this mod and its dependencies? Each dependency must have completed analysis and resolved findings. Approval is your review decision, not a safety guarantee.'))return;try{await api(`mods/${modId}/approve`,{});$('reviewstatus').textContent='Mod and dependencies approved.';}catch(error){$('reviewstatus').textContent=error.message;}});
$('decisioncancel').addEventListener('click',()=>$('findingdecision').close());$('decisionform').addEventListener('submit',async event=>{event.preventDefault();try{await api(`mods/${modId}/analysis/${decisionTarget.id}`,{accepted:!decisionTarget.accepted,reason:$('decisionreason').value,sha256:report.sha256});$('findingdecision').close();await load();}catch(error){$('decisionevidence').textContent=error.message;}});
$('filesearch').addEventListener('input',renderFiles);$('findingfilter').addEventListener('change',renderFindings);window.addEventListener('pagehide',()=>clearTimeout(poll));load();
