'use strict';
let socialReady=false,socialPeer=0,socialMember=0,socialRows=[],socialLoading=false,socialSerial=0,socialPending=null,socialBusy=false,socialBefore=0,socialHistory=false,socialWindowKey='',socialReadSeq=0;
function socialNode(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function socialId(){return crypto.randomUUID();}
function socialActive(){return location.pathname==='/messages'||/^\/messages\/\d+$/.test(location.pathname);}
function socialGuard(result,member){if(currentUser?.id!==member||result.member_id!==member)throw new Error('Your account changed. Reload before continuing.');}
async function socialMutation(path,data){
 if(socialBusy)return;const member=currentUser?.id,key=JSON.stringify({path,data});
 if(socialPending&&(socialPending.member!==member||socialPending.key!==key))throw new Error('Retry your pending action first; its original request prevents duplicates.');
 const pending=socialPending||{path,data,key,member,payload:{...data,request_id:socialId()}};socialBusy=true;let submitted=false,recorded=false;
 try{if(currentUser?.id!==pending.member)throw new Error('Your account changed. Reload.');submitted=true;const result=await json(path,pending.payload,{headers:{'X-Canna-Member':String(member)}});recorded=true;socialPending=null;socialGuard(result,member);return result;}
 catch(error){if(submitted&&!recorded&&(!Number.isInteger(error.status)||error.status>=500))socialPending=pending;throw error;}
 finally{socialBusy=false;socialControls();}
}
function socialControls(){const locked=socialBusy||!!socialPending;for(const n of document.querySelectorAll('#friendsview button[data-mutation]'))n.disabled=locked||n.dataset.unavailable==='true';const retry=$('social-retry');if(retry){retry.hidden=!socialPending;retry.disabled=socialBusy||socialPending?.member!==currentUser?.id;}$('dm-send')?.toggleAttribute('disabled',locked||$('dm-send').dataset.unavailable==='true');}
function setupSocial(){
 if(socialReady)return;socialReady=true;const root=$('friendsview');root.append(socialNode('h2','Friends & private messages'),socialNode('p','Accept a friend request to exchange private messages and share a modpack.'));
 const tools=socialNode('div',undefined,'row');tools.append(button('Find members',()=>navigatePage('/members'),'/members'),button('Refresh friends',()=>loadSocial()));const retry=button('Retry pending action',async()=>{if(!socialPending)return;const pending=socialPending;await socialMutation(pending.path,pending.data);if(pending.path==='social/messages'&&$('dm-body').value===pending.data.body){$('dm-body').value='';$('dm-pack').value='';}await loadSocial();});retry.id='social-retry';retry.hidden=true;tools.append(retry);root.append(tools);
 const status=socialNode('p');status.id='social-status';status.setAttribute('role','status');root.append(status);
 const layout=socialNode('div',undefined,'social-layout'),aside=socialNode('aside',undefined,'social-sidebar');for(const [id,title]of [['social-friends','Friends'],['social-requests','Requests'],['social-conversations','Recent conversations'],['social-blocks','Blocked members']]){aside.append(socialNode('h3',title));const list=socialNode('div');list.id=id;aside.append(list);}
 const conversation=socialNode('section',undefined,'social-conversation');conversation.id='dm-conversation';const heading=socialNode('h3','Choose a friend');heading.id='dm-heading';const older=button('Older messages',()=>loadConversation(true));older.id='dm-older';older.hidden=true;const messages=socialNode('div');messages.id='dm-messages';messages.setAttribute('role','log');messages.setAttribute('aria-label','Private messages');
 const form=socialNode('form');form.id='dm-form';form.hidden=true;const bodyLabel=socialNode('label','Message'),body=socialNode('textarea');body.id='dm-body';body.maxLength=4000;body.rows=3;bodyLabel.append(body);const packLabel=socialNode('label','Attach shared modpack (optional)'),pack=socialNode('input');pack.id='dm-pack';pack.placeholder='Paste a Canna shared pack link';packLabel.append(pack);const send=socialNode('button','Send private message');send.type='submit';send.id='dm-send';send.dataset.mutation='true';form.append(bodyLabel,packLabel,send);
 form.addEventListener('submit',event=>{event.preventDefault();action(async()=>{if(!socialPeer||socialBusy)return;const data={target:socialPeer,body:body.value};if(pack.value.trim()){const value=pack.value.trim(),match=value.match(/^[a-f0-9-]{36}$/i)||value.match(/^https:\/\/cannamods\.vip\/packs\/([a-f0-9-]{36})\/?$/i);if(!match)throw new Error('Attach a Canna shared modpack link.');data.pack_id=match[1]||match[0];}await socialMutation('social/messages',data);body.value='';pack.value='';await loadConversation();await loadSocialOverview();});});
 const latest=button('Latest messages',()=>loadConversation());latest.id='dm-latest';latest.hidden=true;conversation.append(heading,older,latest,messages,form);layout.append(aside,conversation);root.append(layout);
}
function socialActionButton(label,target,verb){const b=button(label,async()=>{if(['remove','block'].includes(verb)&&!await cannaConfirm(verb==='block'?'Block this member and remove the friendship?':'Remove this friend or request?'))return;await socialMutation('social/friends',{target,action:verb});await loadSocial();});b.dataset.mutation='true';return b;}
async function loadSocialOverview(){
 const member=currentUser.id,serial=++socialSerial,result=await(await api('social')).json();if(serial!==socialSerial||!socialActive())return;socialGuard(result,member);
 for(const id of ['social-friends','social-requests','social-conversations','social-blocks'])$(id).replaceChildren();
 for(const friend of result.friends){const row=socialNode('div',undefined,'social-friend'),open=button(friend.username,()=>navigatePage('/messages/'+friend.id),'/messages/'+friend.id);row.append(open);if(friend.status==='accepted'){row.append(socialActionButton('Remove',friend.id,'remove'));$('social-friends').append(row);}else{row.append(socialNode('small',friend.requester===member?'Sent request':'Incoming request'));if(friend.requester!==member)row.append(socialActionButton('Accept',friend.id,'accept'));row.append(socialActionButton(friend.requester===member?'Cancel':'Decline',friend.id,'remove'));$('social-requests').append(row);}}
 for(const person of result.conversations){const b=button(person.username+(person.unread?' · '+person.unread+' unread':''),()=>navigatePage('/messages/'+person.id),'/messages/'+person.id);$('social-conversations').append(b);}
 for(const person of result.blocks){const row=socialNode('div',undefined,'social-friend');row.append(socialNode('span',person.username),socialActionButton('Unblock',person.id,'unblock'));$('social-blocks').append(row);}
 if(!$('social-friends').children.length)$('social-friends').append(socialNode('p','No friends yet. Find someone in Members and send a request.'));socialControls();
}
async function loadSocial(){setupSocial();if(!socialActive())return;const member=currentUser.id,peer=Number(location.pathname.split('/')[2])||0;if(socialMember!==member){socialMember=member;socialPeer=0;socialRows=[];socialWindowKey='';socialReadSeq=0;socialBefore=0;socialHistory=false;conversationSerial++;$('dm-body').value='';$('dm-pack').value='';}if(peer!==socialPeer){socialWindowKey='';socialReadSeq=0;socialHistory=false;socialPeer=peer;socialRows=[];socialBefore=0;$('dm-body').value='';$('dm-pack').value='';$('dm-messages').replaceChildren();}await loadSocialOverview();if(!socialActive()||currentUser.id!==member)return;if(peer)await loadConversation();else{$('dm-form').hidden=true;$('dm-heading').textContent='Choose a friend';$('dm-messages').replaceChildren();$('dm-older').hidden=true;$('dm-latest').hidden=true;}socialControls();}
let conversationSerial=0;
async function loadConversation(older=false){
 if(!socialPeer||!socialActive())return;const member=currentUser.id,peer=socialPeer,serial=++conversationSerial;
 const result=await(await api(`social/messages/${peer}`+(older?'?before='+socialBefore:''))).json();if(serial!==conversationSerial||!socialActive()||socialPeer!==peer)return;socialGuard(result,member);
 socialRows=result.messages;socialHistory=older;socialBefore=socialRows[0]?.seq||0;$('dm-older').hidden=!result.has_more;$('dm-latest').hidden=!older;
 const snapshot=JSON.stringify([peer,result.can_send,socialRows]);if(snapshot===socialWindowKey){socialControls();return;}socialWindowKey=snapshot;
 $('dm-heading').textContent='Private conversation';$('dm-form').hidden=false;$('dm-send').dataset.unavailable=String(!result.can_send);$('dm-messages').replaceChildren(...socialRows.map(item=>{
  const row=socialNode('article',undefined,'dm-message '+(item.sender===member?'outgoing':'incoming'));row.append(socialNode('small',(item.sender===member?'You':'Friend')+' · '+new Date(item.created*1000).toLocaleString()));if(item.body)row.append(socialNode('p',item.body,'postbody'));
  if(item.pack){const card=socialNode('div',undefined,'dm-pack'),pack=item.pack;card.append(socialNode('strong',pack.name),socialNode('p',`${pack.game||''} · ${pack.mod_count??0} mods${pack.author?' · by '+pack.author:''}`));if(pack.available){const id=pack.id;if(/^[a-f0-9-]{36}$/i.test(id))card.append(button('Open modpack / download to Canna',()=>navigatePage('/packs/'+id),'/packs/'+id));}else card.append(socialNode('small',pack.requires_beta?'Canna Bliss Beta access is required.':'This shared pack is unavailable.'));row.append(card);}return row;
 }));if(!socialRows.length)$('dm-messages').append(socialNode('p','Start the conversation.'));if(!result.can_send)$('social-status').textContent='Accept a friendship to send messages. Your existing conversation stays available.';else $('social-status').textContent='';socialControls();
 if(!older&&result.next>socialReadSeq&&!document.hidden){await json('social/messages/read',{peer,seq:result.next},{headers:{'X-Canna-Member':String(member)}});socialReadSeq=result.next;}
}
async function renderFriendActions(target,current){
 let root=$('profile-friends');if(!root){root=socialNode('div',undefined,'row');root.id='profile-friends';$('profilecard').append(root);}root.replaceChildren();if(target===currentUser.id){root.append(button('Friends & messages',()=>navigatePage('/messages'),'/messages'));return;}
 const member=currentUser.id,result=await(await api('social/relationships/'+target)).json();if(!current())return;socialGuard(result,member);const state=result.status;
 const perform=verb=>async()=>{await socialMutation('social/friends',{target,action:verb});if(current())await renderFriendActions(target,current);};
 if(state==='none')root.append(button('Add friend',perform('request')));if(state==='incoming')root.append(button('Accept friend',perform('accept')));if(state==='outgoing')root.append(socialNode('small','Friend request sent'));
 if(state==='friends')root.append(button('Private message',()=>navigatePage('/messages/'+target),'/messages/'+target));if(['friends','incoming','outgoing'].includes(state))root.append(button('Remove friendship / request',perform('remove')));if(state!=='blocked')root.append(button('Block member',async()=>{if(await cannaConfirm('Block this member?'))await perform('block')();}));
}
$('friendsnav')?.addEventListener('click',()=>action(()=>navigatePage('/messages')));
setInterval(()=>{if(!socialReady||!socialActive()||document.hidden||socialBusy||socialLoading)return;socialLoading=true;Promise.resolve().then(async()=>{if(socialPeer&&!socialHistory)await loadConversation();await loadSocialOverview();}).catch(error=>{$('social-status').textContent=error.message;}).finally(()=>socialLoading=false);},5000);
