'use strict';
const el=id=>document.getElementById(id);let proof,proofAt=0,currentTicket='',ticketKey='';
async function supportApi(path,options={}){const response=await fetch('/api/v1/'+path,options);if(!response.ok)throw new Error((await response.json().catch(()=>({}))).error||'Request failed');return response.status===204?null:response.json();}
function ticketHeaders(){return {'Content-Type':'application/json',...(ticketKey?{'x-canna-ticket':ticketKey}:{})};}
async function prepareProof(){const c=await supportApi('support/challenge',{method:'POST'});const encoded=new TextEncoder();for(let nonce=0;nonce<1000000;nonce++){const hash=new Uint8Array(await crypto.subtle.digest('SHA-256',encoded.encode(c.seed+':'+nonce)));if(hash[0]===0 && (hash[1]&240)===0){proofAt=Date.now();return {seed:c.seed,nonce};}if(nonce%100===0)await new Promise(r=>setTimeout(r,0));}throw new Error('Verification could not finish. Refresh this page.');}
function resetProof(){proof=prepareProof().catch(e=>{el('ticketnotice').textContent=e.message;return null;});}resetProof();
el('ticketform').addEventListener('submit',async e=>{e.preventDefault();el('ticketsubmit').disabled=true;el('ticketnotice').textContent='Submitting your ticket…';try{let p=await proof;if(!p || Date.now()-proofAt>540000){resetProof();p=await proof;}if(!p)throw new Error('Reload the form to verify.');await new Promise(r=>setTimeout(r,2200));const v=await supportApi('support/tickets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...p,subject:el('ticketsubject').value,category:el('ticketcategory').value,body:el('ticketbody').value,website:el('ticketwebsite').value,fax:el('ticketfax').value})});currentTicket=v.id;ticketKey=v.key;location.hash=new URLSearchParams({ticket:v.id,key:v.key});el('ticketform').reset();el('ticketnotice').textContent='Ticket submitted. Save your tracking link to return to this conversation.';await openTicket();resetProof();}catch(err){el('ticketnotice').textContent=err.message;resetProof();}finally{el('ticketsubmit').disabled=false;}});
async function openTicket(){const v=await supportApi('support/tickets/'+currentTicket,{headers:ticketHeaders()});el('ticketdetail').hidden=false;el('tickettitle').textContent=v.subject;el('ticketstate').textContent=v.category+' · '+v.status;el('tracking').hidden=!ticketKey;el('trackinglink').href=location.href;el('trackinglink').textContent='Save this link';el('ticketmessages').replaceChildren(...v.messages.map(m=>{const n=document.createElement('article');n.className='entry';const author=document.createElement('strong');author.textContent=m.staff?'Canna staff':'You';const body=document.createElement('p');body.className='postbody';body.textContent=m.body;const time=document.createElement('small');time.textContent=new Date(m.created*1000).toLocaleString();n.append(author,body,time);return n;}));el('ticketreplyform').hidden=v.status==='closed';}
el('ticketreplyform').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await supportApi('support/tickets/'+currentTicket+'/reply',{method:'POST',headers:ticketHeaders(),body:JSON.stringify({body:el('ticketreply').value})});el('ticketreply').value='';await openTicket();}catch(err){el('ticketnotice').textContent=err.message;}finally{b.disabled=false;}});
el('ticketrefresh').onclick=()=>openTicket().catch(e=>el('ticketnotice').textContent=e.message);el('copytracking').onclick=()=>navigator.clipboard.writeText(location.href).then(()=>el('ticketnotice').textContent='Tracking link copied. Keep it private.').catch(()=>el('ticketnotice').textContent='Copy the URL from your address bar.');
const params=new URLSearchParams(location.hash.slice(1));if(params.has('ticket')){currentTicket=params.get('ticket');ticketKey=params.get('key')||'';openTicket().catch(e=>el('ticketnotice').textContent=e.message);}
supportApi('support/tickets').then(rows=>{el('mytickets').hidden=false;el('myticketlist').replaceChildren(...rows.map(t=>{const b=document.createElement('button');b.type='button';b.className='ticketlink';b.textContent=t.subject+' · '+t.status;b.onclick=()=>{currentTicket=t.id;ticketKey='';location.hash=new URLSearchParams({ticket:t.id});openTicket().catch(e=>el('ticketnotice').textContent=e.message);};return b;}));}).catch(()=>{});
