<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>Canna.DuctTapePlusPlus.SmokeChecks</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <Managed Condition="'$(Managed)' == ''">$(GameDir)/ROUNDS_Data/Managed</Managed>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472" Version="1.0.3" PrivateAssets="all" />
    <Compile Include="SmokeChecks.cs" />
    <Reference Include="$(GameDir)/BepInEx/core/BepInEx.dll" Private="false" />
    <Reference Include="$(GameDir)/BepInEx/core/0Harmony.dll" Private="false" />
    <Reference Include="$(Managed)/Assembly-CSharp.dll" Private="false" />
    <Reference Include="$(Managed)/UnityEngine.dll" Private="false" />
    <Reference Include="$(Managed)/UnityEngine.CoreModule.dll" Private="false" />
    <Reference Include="$(Managed)/PhotonRealtime.dll" Private="false" />
    <Reference Include="$(Managed)/PhotonUnityNetworking.dll" Private="false" />
    <Reference Include="$(Managed)/Photon3Unity3D.dll" Private="false" />
    <Reference Include="$(Managed)/InControl.dll" Private="false" />
    <Reference Include="$(Managed)/netstandard.dll" Private="false" />
  </ItemGroup>
</Project>
