// Actual browser DOM and production handlers with synthetic HTTP only.
const fs=require('node:fs'),assert=require('node:assert/strict');
const {chromium}=require(process.env.CANNA_PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 try{
 for(const width of [1280,390]){
  const page=await browser.newPage({viewport:{width,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/*',route=>route.fulfill({status:200,contentType:'text/html',body:'<html></html>'}));await page.goto('https://canna-fixture.invalid/gambling');
  await page.setContent(`<style>[hidden]{display:none!important}${fs.readFileSync('server/web/forum.css','utf8')}${fs.readFileSync('server/web/admin-games.css','utf8')}</style><main><div id="space"><div></div><div></div></div><span id="kashbalance"></span><section id="gamblingview"></section><section id="moderation"><section id="admin-gambling"></section><section id="admin-economy"><div id="walletlist"></div></section></section></main>`);
  await page.evaluate(()=>{
   window.$=id=>document.getElementById(id);window.currentUser={id:1,username:'Owner',role:'owner',admin:true,kash:1000};window.action=fn=>fn();window.message=()=>{};window.button=(label,fn)=>{const n=document.createElement('button');n.textContent=label;n.type='button';n.addEventListener('click',()=>fn());return n;};window.cannaConfirm=async()=>true;window.openProfile=()=>{};window.loadNotifications=async()=>{};window.listPages=new Map();window.apiCalls=[];window.posts=[];
   window.rules={paused:false,daily_limit:200,games:['crash','blackjack','roulette','dice','slots','cases'].map(game=>({game,enabled:true,min_stake:1,max_stake:1000000,payout_percent:game==='dice'?95:100})),crates:['bo2-calling-cards','mw2-calling-cards','avatar-frames','canna-case'].map(case_id=>({case_id,cost:100}))};
   window.crash={id:1,phase:'betting',mode:'random',paused:false,betting_ends_ms:Date.now()+10000,multiplier:1,history:[],participants:[],participant_count:0};
   window.state={member_id:1,wallet:{balance:1000,daily_available:true},notice:'Synthetic Kash game',server_time_ms:Date.now(),crash,blackjack:null,rules,recent_games:[],cosmetics:{catalog_version:'a'.repeat(64),owned:[],equipped:{frame:null,banner:null}}};
   window.catalog={version:'a'.repeat(64),catalog:[{id:'frame-fixture',name:'Frame',kind:'frame',collection:'frames',rarity:'common'}],cases:['bo2-calling-cards','mw2-calling-cards','avatar-frames'].map(id=>({id,name:id,cost:100,collection:id==='avatar-frames'?'frames':id.slice(0,3),available:id!=='mw2-calling-cards',items:[]}))};
   window.walletRows=[{id:1,username:'Owner',balance:1000,earned:100}];window.holdWallet=null;window.heldWalletReply=null;
   window.api=async path=>{apiCalls.push(path);let data;if(path==='me')data={...currentUser,kash:777};else if(path.startsWith('chat/tip-recipients?'))data={items:[{id:1,username:'Owner'},{id:2,username:'Alice'},{id:3,username:'Alfred'}]};else if(path==='chat'||path==='chat/history')data=[];else if(path==='admin/gambling')data={mode:'random',paused:false,queue:[],crash,rules,metrics:{arcade_games_24h:1,arcade_staked_24h:25,arcade_paid_24h:50,active_blackjack_hands:0,pending_crash_bets:0},planned_crash_multiplier:1000,planned_crash_at_ms:Date.now()+50000};else if(path.startsWith('admin/wallets')){if(holdWallet)await new Promise(r=>heldWalletReply=r);data={items:walletRows};}else if(path==='gambling/cosmetics/catalog')data=catalog;else if(path.startsWith('gambling?'))data=state;else throw new Error('Unexpected fixture route '+path);return{json:async()=>structuredClone(data)};};
   window.loseTipReply=false;window.json=async(path,payload)=>{posts.push({path,payload:structuredClone(payload)});if(path==='chat'){if(loseTipReply){loseTipReply=false;throw new TypeError('Synthetic lost tip response');}return{id:10};}if(path==='admin/gambling/rules'){window.rules=structuredClone(payload);state.rules=rules;return{rules};}if(path==='admin/gambling')return{};if(path==='gambling/arcade/play'){const result={game:payload.game,stake:payload.stake,payout:50,created:Math.floor(Date.now()/1000),result:payload.game==='roulette'?{number:7,color:'red',choice:payload.choice,pick:payload.number??null}:payload.game==='dice'?{roll:12.34,under:payload.under}:{reels:[0,0,0]}};state.recent_games=[result];return result;}return{};};
   window.pagedList=async()=>walletRows;
  });
  for(const file of ['gambling.js','admin.js','lounge.js'])await page.addScriptTag({content:fs.readFileSync('server/web/'+file,'utf8')});
  await page.evaluate(async()=>{gamblingRouteActive=()=>true;await loadGambling();await loadGamblingAdmin();await loadWallets();setupLounge();listPages.set('walletlist',{page:1,search:{value:''}});});
  for(const [tab,button]of [['roulette','Spin wheel'],['dice','Roll dice'],['slots','Spin reels']]){
   await page.evaluate(tab=>selectGamblingTab(tab),tab);await page.getByRole('button',{name:button,exact:true}).click();await page.waitForFunction(()=>!gamblingBusy);assert(await page.locator('#'+tab+'-result').textContent(),JSON.stringify(await page.evaluate(()=>({posts,status:$('gambling-status').textContent,valid:$('gambling-roulette').querySelector('form').checkValidity(),html:$('gambling-roulette').innerHTML}))));
  }
  await page.evaluate(()=>selectGamblingTab('roulette'));await page.locator('#roulette-choice').selectOption('number');assert(await page.locator('#roulette-number').isVisible());await page.locator('#roulette-number').fill('36');await page.getByRole('button',{name:'Spin wheel',exact:true}).click();await page.waitForFunction(()=>!gamblingBusy);assert.equal(await page.evaluate(()=>posts.filter(p=>p.path==='gambling/arcade/play').at(-1).payload.number),36);
  await page.locator('#admin-house-paused').check();await page.locator('#admin-rule-slots-payout_percent').fill('150');await page.getByRole('button',{name:'Save game controls',exact:true}).click();await page.waitForFunction(()=>posts.some(p=>p.path==='admin/gambling/rules'));await page.evaluate(()=>loadGambling());assert(await page.locator('#roulette-play').isDisabled());assert(await page.locator('#slots-play').isDisabled());
  assert.equal(await page.locator('#crash-auto').getAttribute('max'),'1000');await page.evaluate(()=>addCrashQueueRow({min_multiplier:1000,max_multiplier:1000,rounds:1}));assert.equal(await page.locator('#admin-crash-queue-editor [data-field="max"]').getAttribute('max'),'1000');await page.getByRole('button',{name:'Save Crash settings & queue',exact:true}).click();await page.waitForFunction(()=>posts.some(p=>p.path==='admin/gambling'));assert.equal(await page.evaluate(()=>posts.find(p=>p.path==='admin/gambling').payload.queue[0].max_multiplier),1000);
  // Presets select future random rounds without entering ranges; stake caps
  // follow the current wallet rather than legacy per-game limits.
  await page.locator('[data-luck-preset="10000"]').click();
  assert.equal(await page.locator('#admin-crash-luck').inputValue(),'10000');assert.equal(await page.locator('#admin-crash-queue-editor>div').count(),0);
  assert.equal(await page.locator('#admin-rule-slots-max_stake').count(),0);
  await page.getByRole('button',{name:'Save Crash settings & queue',exact:true}).click();await page.waitForFunction(()=>posts.filter(p=>p.path==='admin/gambling').length===2);
  assert.equal(await page.evaluate(()=>posts.filter(p=>p.path==='admin/gambling').at(-1).payload.luck_percent),10000);
  assert.equal(await page.evaluate(()=>posts.filter(p=>p.path==='admin/gambling').at(-1).payload.mode),'random');
  await page.evaluate(async()=>{state.wallet.balance=3000000;state.rules.paused=false;await loadGambling();selectGamblingTab('slots');});
  assert.equal(await page.locator('#slots-stake').getAttribute('max'),'3000000');await page.locator('#slots-stake').fill('2000000');assert(await page.locator('#gambling-slots form').evaluate(n=>n.checkValidity()));
  await page.getByRole('button',{name:'Spin reels',exact:true}).click();await page.waitForFunction(()=>!gamblingBusy);
  assert.equal(await page.evaluate(()=>posts.filter(p=>p.path==='gambling/arcade/play').at(-1).payload.stake),2000000);
  await page.evaluate(()=>{walletRows[0].balance=2000;walletRows[0].earned=150;});await page.locator('[data-wallet-field="balance"]').fill('345');await page.locator('#walletlist input[placeholder="Reason for adjustment"]').fill('Keep this reason');await page.evaluate(()=>refreshAdminWallets());assert.equal(await page.locator('[data-wallet-field="balance"]').inputValue(),'345');assert.equal(await page.locator('[data-wallet-field="earned"]').inputValue(),'150');assert.equal(await page.locator('#walletlist input[placeholder="Reason for adjustment"]').inputValue(),'Keep this reason');assert.match(await page.locator('[data-wallet-live]').textContent(),/2,000 Kash/);assert.equal(await page.locator('#kashbalance').textContent(),'777 Kash');
  if(!await page.locator('#chatbody').isVisible())await page.locator('#globalchat>summary').click();await page.locator('#chatbody').fill('/tip Al');await page.waitForSelector('#tip-option-0');assert.equal(await page.locator('#tip-suggestions button').count(),2);await page.locator('#chatbody').press('ArrowDown');await page.locator('#chatbody').press('Enter');assert.equal(await page.locator('#chatbody').inputValue(),'/tip @Alice ');await page.locator('#chatbody').fill('/tip @Alice 25');await page.evaluate(()=>loseTipReply=true);await page.locator('#chatform button[type="submit"]').click();await page.waitForFunction(()=>document.getElementById('chatstatus').textContent.includes('same message'));await page.locator('#chatform button[type="submit"]').click();await page.waitForFunction(()=>document.getElementById('chatbody').value==='');assert.equal(await page.evaluate(()=>posts.filter(p=>p.path==='chat')[0].payload.request_id===posts.filter(p=>p.path==='chat')[1].payload.request_id),true);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.deepEqual(errors,[]);await page.screenshot({path:`target/arcade-preview-${width}.png`,fullPage:true});await page.close();console.log(`${width}px: games, rule controls, 1000x queue, wallet drafts and autocomplete/retry passed`);
 }
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
