const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
async function fixture(role,failed=false){const fields=new Map();const all=[];function node(tag){const n={tag,children:[],hidden:false,value:'',dataset:{},className:'',classList:{toggle(){}},textContent:'',setAttribute(){},addEventListener(){},append(...nodes){this.children.push(...nodes);},prepend(...nodes){this.children.unshift(...nodes);},querySelector(tag){return this.children.find(n=>n.tag===tag)||node(tag);},replaceChildren(...nodes){this.children=nodes;},get lastChild(){return this.children.at(-1);}};all.push(n);return n;}
for(const id of ['moderation','memberlist','sectionmanager','ownercontrols','ownerlog','admin','newwave']){const n=node('div');n.id=id;fields.set(id,n);}
const get=id=>fields.get(id)||all.find(n=>n.id===id);const calls=[];let reviewed=false;
const ctx=vm.createContext({currentUser:{role,admin:true},$:get,document:{createElement:node,querySelectorAll:s=>s==='.admintabs button'?all.filter(n=>n.dataset.tab):all.filter(n=>n.id?.startsWith('admin-'))},button:(label,fn)=>{const n=node('button');n.textContent=label;n.click=fn;return n;},api:async path=>({json:async()=>path==='admin/overview'?{members:2,pending:reviewed?0:1,storage_bytes:100,version:'fixture'}:path==='admin/mod-reviews'?(reviewed?[]:[{id:'mod',name:'Fixture',version:'1',author:'uploader',size:100,app_id:1686940}]):[]}),json:async path=>{calls.push(path);if(failed)throw Error('Resolve suspicious-code findings in the review workspace before approval');reviewed=true;},cannaConfirm:async()=>true,setupLoungeAdmin(){},loadLoungeAdmin:async()=>{},viewSource:async id=>calls.push('source:'+id),message(){},activity:()=>'',console});
ctx.pagedList=async path=>(await ctx.api(path)).json();
vm.runInContext(fs.readFileSync('server/web/admin.js','utf8'),ctx);vm.runInContext('setupAdmin()',ctx);
const tabs=all.filter(n=>n.dataset.tab).map(n=>n.dataset.tab);assert.equal(tabs.includes('tickets'),true);assert.equal(tabs.includes('reviews'),true);assert.equal(tabs.includes('invitations'),role==='owner');assert.equal(tabs.includes('sections'),role==='owner');
await vm.runInContext('loadModReviews()',ctx);const approve=all.find(n=>n.textContent==='Approve with dependencies');await approve.click();assert.deepEqual(calls,['mods/mod/approve']);if(failed){assert(all.some(n=>n.textContent==='Resolve suspicious-code findings in the review workspace before approval'));assert.equal(approve.disabled,false);assert.equal(reviewed,false);}else assert.equal(get('modreviewlist').textContent,'No mods awaiting review.');
await vm.runInContext("selectAdminTab('tickets')",ctx);assert.equal(get('admin-tickets').hidden,false);assert.equal(get('admin-reviews').hidden,true);}
(async()=>{await fixture('owner');await fixture('admin');await fixture('owner',true);console.log('Admin tabs, owner-only controls, approval queue and ticket navigation passed.');})().catch(e=>{console.error(e);process.exitCode=1;});
